apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - image: tariqulislam/mdn-test-library-docker
          name: {{ .Values.appName }}
          command: ["sh", "-c"]
          args:
            - |
               /bin/sh <<'EOF'
                  python manage.py createsuperuser --noinput
                  python manage.py runserver 0.0.0.0:8000
                  exit 123
               EOF
          envFrom:
            - configMapRef:
                name: django-config-map          
          env:
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-user-pass
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: admin-user-pass
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user-pass
                  key: DJANGO_SUPERUSER_PASSWORD

          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.service.port }}